"use strict";
var angular = require('angular');
var norApp = angular.module('norApp');
norApp.directive('norAction', require('./norAction/directive.js'));
norApp.directive('autoFocus', require('./autoFocus/directive.js'));
norApp.directive('ngEnter', require('./ngEnter/directive.js'));
norApp.directive('norAction', require('./norAction/directive.js'));
norApp.directive('norDropdown', require('./norDropdown/directive.js'));
norApp.directive('norEditableContent', require('./norEditableContent/directive.js'));
norApp.directive('norForm', require('./norForm/directive.js'));
norApp.directive('norLink', require('./norLink/directive.js'));
norApp.directive('norRecord', require('./norRecord/directive.js'));
norApp.directive('norSchemaArray', require('./norSchemaArray/directive.js'));
norApp.directive('norSchemaBoolean', require('./norSchemaBoolean/directive.js'));
norApp.directive('norSchemaCustom', require('./norSchemaCustom/directive.js'));
norApp.directive('norSchema', require('./norSchema/directive.js'));
norApp.directive('norSchemaNumber', require('./norSchemaNumber/directive.js'));
norApp.directive('norSchemaString', require('./norSchemaString/directive.js'));
norApp.directive('norSelect', require('./norSelect/directive.js'));
norApp.directive('norTable', require('./norTable/directive.js'));
norApp.directive('norType', require('./norType/directive.js'));
